version: '3.8'
services:
  hell_core:
    build: .
    container_name: hell_core
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - ./logs:/app/logs
      - ./scripts:/app/scripts
      - ./payloads:/app/payloads
      - ./templates:/app/templates
    environment:
      - MY_IP=${MY_IP}
      - VT_API_KEY=${VT_API_KEY}

  win7_accounting:
    image: dockur/windows:latest
    container_name: win7_accounting
    environment:
      VERSION: "7"
      RAM_SIZE: "1.5G"
      CPU_CORES: "1"
    ports:
      - "33891:3389"
    volumes:
      - ./assets/robbable:/shared
    restart: always

  win7_developer:
    image: dockur/windows:latest
    container_name: win7_developer
    environment:
      VERSION: "7"
      RAM_SIZE: "1.5G"
      CPU_CORES: "1"
    ports:
      - "33892:3389"
    volumes:
      - ./assets/robbable:/shared
    restart: always

  winxp_scada:
    image: dockur/windows:latest
    container_name: winxp_scada
    environment:
      VERSION: "winxp"
      RAM_SIZE: "512M"
    ports:
      - "33893:3389"
    volumes:
      - ./assets/robbable:/shared
    restart: always

  winxp_office:
    image: dockur/windows:latest
    container_name: winxp_office
    environment:
      VERSION: "winxp"
      RAM_SIZE: "512M"
    ports:
      - "33894:3389"
    volumes:
      - ./assets/robbable:/shared
    restart: always

  hell_db:
    image: mysql:8.0
    container_name: hell_db_backend
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: hell_forensics
    ports:
      - "33060:3306"
