version: '3.8'
services:
  hell_core:
    build: .
    container_name: hell_core
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - ./logs:/app/logs
      - ./scripts:/app/scripts
      - ./payloads:/app/payloads
      - ./templates:/app/templates
    environment:
      - MY_IP=${MY_IP}
      - VT_API_KEY=${VT_API_KEY}

  hell_db:
    image: mysql:8.0
    container_name: hell_db_backend
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: INK0uJ8j4a5xCn
      MYSQL_DATABASE: hell_forensics
    ports:
      - "33060:3306"
