version: '3.8'
services:
  hell_core:
    build: .
    container_name: hell_core
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - ./logs:/app/logs
      - ./scripts:/app/scripts
      - ./payloads:/app/payloads
      - ./templates:/app/templates
      - ./assets:/app/assets
    environment:
      - MY_IP=${MY_IP}
      - VT_API_KEY=${VT_API_KEY}
      - DB_PASSWORD=${DB_PASSWORD}

  win7_accounting:
    image: dockurr/windows:latest
    container_name: win7_accounting
    environment:
      VERSION: "7"
      RAM_SIZE: "1G"
    ports:
      - "44891:3389"
      - "8006:8006"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    volumes:
      - ./assets/robbable:/shared
    restart: always

  win7_developer:
    image: dockurr/windows:latest
    container_name: win7_developer
    environment:
      VERSION: "7"
      RAM_SIZE: "1G"
    ports:
      - "44892:3389"
      - "8007:8006"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    volumes:
      - ./assets/robbable:/shared
    restart: always

  winxp_scada:
    image: dockurr/windows:latest
    container_name: winxp_scada
    environment:
      VERSION: "winxp"
      RAM_SIZE: "512M"
    ports:
      - "44893:3389"
      - "8008:8006"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    volumes:
      - ./assets/robbable:/shared
    restart: always

  winxp_office:
    image: dockurr/windows:latest
    container_name: winxp_office
    environment:
      VERSION: "winxp"
      RAM_SIZE: "512M"
    ports:
      - "44894:3389"
      - "8009:8006"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    volumes:
      - ./assets/robbable:/shared
    restart: always

  hell_db:
    image: mysql:8.0
    container_name: hell_db_backend
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: hell_forensics
    ports:
      - "33060:3306"
