import os
import time

def generate_formal_report(ip, asn, location, ja3, duration, data_mb):
    """Genera una queja formal de abuso con evidencia técnica"""
    os.makedirs("logs/abuse_reports", exist_ok=True)
    timestamp = time.strftime('%Y-%m-%d %H:%M:%S')
    filename = f"logs/abuse_reports/REPORT_{ip}_{int(time.time())}.txt"
    
    report_body = f"""ABUSE INCIDENT REPORT - GENERATED BY HELL ACTIVE DEFENSE
======================================================
Date/Time: {timestamp}
Source IP: {ip}
Network (ASN): {asn}
Origin Location: {location}

INCIDENT DETAILS:
-----------------
The IP address {ip} has been detected performing highly aggressive malicious activity
against our infrastructure. The behavior includes unauthorized access attempts and
resource exhaustion attacks.

TECHNICAL EVIDENCE:
- TLS Fingerprint (JA3): {ja3 if ja3 else 'N/A'}
- Active Engagement Duration: {duration} seconds
- Data Buffer Impact: {data_mb} MB of null-logic traffic successfully absorbed.
- Connection Profile: High-persistence automated bot.

This activity violates acceptable use policies. Please investigate and terminate
the offending account or server associated with this source IP.

Generated by: HELL Core v8.2.0 Intelligence Node
"""
    
    with open(filename, "w", encoding='utf-8') as f:
        f.write(report_body)
    
    print(f"[📋] Reporte de abuso generado para {ip}: {filename}")
    return filename
